In [ ]:
import numpy as np

In [ ]:
arr = np.array([[2,3],[2,4]])
arr.ndim
arr.dtype
arr.shape
type(arr)


numpy.ndarray

In [ ]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# i want to declare an np array of 3 zeros
a= [1,2,3,4,5]
arr = np.zeros(3)
arr

array([0, 0, 0])

In [ ]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [ ]:
arr = np.full((2,2),[7,3])
arr

array([[7, 3],
       [7, 3]])

In [ ]:
arr= np.array([1,2,3.4,5,6, 'ji'])
arr.dtype

dtype('<U32')

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a*b

array([ 6, 14, 24, 36, 50])

In [ ]:
np.sqrt([4,9,16,25,36])

array([2., 3., 4., 5., 6.])

In [ ]:
np.exp([4,9,16,25,36])

array([5.45981500e+01, 8.10308393e+03, 8.88611052e+06, 7.20048993e+10,
       4.31123155e+15])

In [ ]:
#views

arr = [10,20,30,40,50]
sub = arr[:3]
sub[0] = 5
arr
# arr = np.array([10,20,30,40,50])
# sub = arr[:3]
# sub[0] = 5
# arr

[10, 20, 30, 40, 50]

In [ ]:
matrix = np.array ([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array ([[1,2,3],[4,5,6],[7,8,9]])
matrix @ matrix2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr = matrix.transpose()
arr

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a= [1,2,3]
b = [4,5,6]

print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print( np.concatenate((a,b)))

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr1 = np.array([[1,2,3],[3,4,6]])
arr2 = np.array([[5,6,7],[7,8,9]])
arr3 = np.hstack((arr1,arr2))
arr4 = np.stack((arr1,arr2), axis=0)

print(arr3.shape)
print(arr4.shape)
print(arr3)
print(arr4)

(2, 6)
(2, 2, 3)
[[1 2 3 5 6 7]
 [3 4 6 7 8 9]]
[[[1 2 3]
  [3 4 6]]

 [[5 6 7]
  [7 8 9]]]


In [ ]:
arr1 = np.array([[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6]])
arr2 = np.array([[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6],[1,2,3],[3,4,6]])
arr3 = np.hstack((arr1,arr2))
arr3
np.split(arr3, 5)

[array([[1, 2, 3, 1, 2, 3],
        [3, 4, 6, 3, 4, 6]]),
 array([[1, 2, 3, 1, 2, 3],
        [3, 4, 6, 3, 4, 6]]),
 array([[1, 2, 3, 1, 2, 3],
        [3, 4, 6, 3, 4, 6]]),
 array([[1, 2, 3, 1, 2, 3],
        [3, 4, 6, 3, 4, 6]]),
 array([[1, 2, 3, 1, 2, 3],
        [3, 4, 6, 3, 4, 6]])]

#Type casting astype

In [ ]:
arr = np.array([1,3,4,5,6,7])
arr.astype(np.float64)

array([1., 3., 4., 5., 6., 7.])

#random

In [ ]:
np.random.randint(0,10,4)
np.random.rand(6)
np.random.uniform(0,10,4)


array([8.54700676, 1.87752712, 6.48995405, 8.57296279])

#n-dimentional indexing

In [ ]:
arr = np.array([[4,20,4],[3,10,60],[4,6,7]])
arr

array([[ 4, 20,  4],
       [ 3, 10, 60],
       [ 4,  6,  7]])

#Boolean indexing

In [ ]:
arr = np.array([[4,20,4],[3,10,60],[4,6,7]])
arr[arr<5]
np.clip(arr, 5, 15)

array([[ 5, 15,  5],
       [ 5, 10, 15],
       [ 5,  6,  7]])

#Fancy indexing

In [ ]:
arr =np.array([3,4,5,6,7,8,9])
arr[[1,2,4]]

array([4, 5, 7])

#n-dimention iteration

In [ ]:
arr = np.array([[2,3,4,5,6,7],[2,3,4,5,6,7],[2,3,4,5,6,7]])
for i in np.nditer(arr):
  print(i)

2
3
4
5
6
7
2
3
4
5
6
7
2
3
4
5
6
7


#tile vs repeat

In [ ]:
#difference of view and copy

#Where clause

In [ ]:
# just like if-else
arr = np.arange(3,100,10)
arr
np.where(arr<30, 10, arr)

array([10, 10, 10, 33, 43, 53, 63, 73, 83, 93])

#argwhere

In [ ]:
#index where condition is true
np.argwhere(arr<50)

array([[0],
       [1],
       [2],
       [3],
       [4]])

#sum of 2d array

In [ ]:
arr1 = np.array([[2,3,4,5],[7,8,9,0]])
arr2 = np.array([[2,3,4,5],[7,8,9,0]])
np.sum((arr1,arr2), axis=0)

array([[ 4,  6,  8, 10],
       [14, 16, 18,  0]])

#floor, ceil, round

In [ ]:
arr = np.array([3.2,4.3,5.7,7.5,2.4,8.9])
np.round(arr)

array([3., 4., 6., 8., 2., 9.])

#Reshaping

In [ ]:
arr = np.linspace(0,100,30)
arr.reshape(3,2,5)

array([[[  0.        ,   3.44827586,   6.89655172,  10.34482759,
          13.79310345],
        [ 17.24137931,  20.68965517,  24.13793103,  27.5862069 ,
          31.03448276]],

       [[ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
          48.27586207],
        [ 51.72413793,  55.17241379,  58.62068966,  62.06896552,
          65.51724138]],

       [[ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
          82.75862069],
        [ 86.20689655,  89.65517241,  93.10344828,  96.55172414,
         100.        ]]])

#vectorization

In [ ]:
arr = np.array([9,16,25,36,64,100,144])
def square(x):
  return x**4
f = np.vectorize(square)
f(arr)

array([     6561,     65536,    390625,   1679616,  16777216, 100000000,
       429981696])

#linear algebra

In [ ]:
#inverse of matrix
arr1 = np.array([[2,3],[7,8]])
arr1
np.linalg.inv(arr1)

array([[-1.6,  0.6],
       [ 1.4, -0.4]])

In [ ]:
#eigenvalues and eigenvectors
arr1 = np.array([[2,3],[7,8]])
arr1
eigvalues, eigvectors = np.linalg.eig(arr1)
eigvectors

array([[-0.77109239, -0.33361486],
       [ 0.63672327, -0.94270946]])

In [ ]:
#diagnolization
# A = PDP-1
# P = [eigenvectors]
# D = [all values ARE ZERO, diagnol eigen values]
# P-1 = P-1

A = np.array([[2,3],[7,8]])
eigenval, eigvec = np.linalg.eig(A)
P  = eigvec
P_inv = np.linalg.inv(P)
D = np.zeros((2,2))
for i in range(2):
  D[i,i] = eigenval[i]
D
# A = PDP-1
P @ D @ P_inv


array([[2., 3.],
       [7., 8.]])

#var, mean, std

In [ ]:
arr = np.array([3.2,4.3,5.7,7.5,2.4,8.9])
np.var
np.mean
np.std

#Missing Values

In [ ]:
arr = np.array([3.2,4.3,5.7,np.nan,2.4,8.9])
mask = np.isnan(arr)
arr[mask]= 5